development:
  adapter: mysql2
  database: awesomepv_development
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  pool: 5
  database: awesomepv_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
  url: ENV["DATABASE_URL"]