development:
  adapter: mysql2
  host: localhost
  database: awesomepv
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  pool: 5
  database: db/test.sqlite3

production:
  adapter: postgresql
  pool: 5
  host: ec2-54-225-101-119.compute-1.amazonaws.com
  encoding: unicode
  database: d65ije1a0v0be5
  username: bjjobdagawfdkl
  password: XU8jFf4NwymYm8B-yvoUJfwfN5
  port: 5432
